name: bench
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - matplotlib
  - tqdm
  - sentencepiece
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - --extra-index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple/
      - torch
      - transformers
      - optimum[onnxruntime-gpu]
